/*
    Ezra Minty - 1048091


Documentation

    show-normal
                Process - The program iterates through the student data contained within the database file,
                printing the ID, Name, and Scores associated with each student.

                Output - A list of the IDs, Names and Scores of every student in the database.

    show-avg
                Process - The program iterates through the student data contained within the database file,
                printing the ID, Name, Scores and Average Score associated with each student. The program does this by storing the
                score values of the current student within a struct, then using this data to calculate and display the student's average score.

                Output - A list of the IDs, Names, Scores and Average Score of every student in the database.

    find-name
                Process - The program searches the student database for any line where the student search name occurs.
                It the prints the associated information for that particular student.

                Output - On output of all the associated information for the student who has a name which matches the one which
                was entered by the user. In the event that there is no student with a name that matches the one which was searched for,
                the program will throw an error to the user indicating that the student was not found.

    find-id
                Process - This command works similar to the "find-name" command, with the one difference being that it allows the user to find
                a student by their ID in the database system. The ID of students are automatically generated by the program. This ensures that no
                two students share the same ID.

                Output - On output of all the associated information for the student who has an ID which matches the one which
                was entered by the user. In the event that there is no student with an ID that matches the one which was searched for,
                the program will throw an error to the user indicating that the student was not found.

    add
                Process - The program first asks for the name of the student to be added and checks the database to make sure that said student does not already exist.
                If the student does not exist within the database. If not, the program then queries the user for the Scores of the student to be added and then stores this information
                within the struct "newStudent". This information is then appended to the end of the database-text file, successfully adding the student to the database.

    id-avg
                Process - The program first queries the user for the ID of the student whos average score is to be calculated and returned. The program then searches through the database
                file for a student who posses the ID which was being searched for. If this student exists the program will use the values of their scores in order to calculate their average score.

                Output - The ID, Name, Scores and Average Score of the student who has an ID which matches the one entered by the user.

    name-avg
                Process - The program first queries the user for the Name of the student whos average score is to be calculated and returned. The program then searches through the database
                file for a student who posses the Name which was being searched for. If this student exists the program will use the values of their scores in order to calculate their average score.

                Output - The ID, Name, Scores and Average Score of the student who has a Name which matches the one entered by the user.

    update-score
                Process - The user if first prompted by the program for the ID of the student whos score is to be changed. This is then used to search for the student within the database. If the student is found
                the user is then prompted for a value which represents the Subject whos score they would like to change, with 1 being Math, 2 being English, 3 being Science and 4 being Social Studies. After this step,
                the program then prompts the user for new subject score. At this point, if the operation is valid, the program then copies the contents of the database file, including the changed score, to the database_alt.txt file.
                This file is then made the main database.txt file while the previous database.txt file is deleted and recreated.

    help
                Process - To assist the user, the software displays a list of available commands, along with descriptions.
                Operation - The program displays the command selected by user, which is included by the command word (e.g. “add”)

    cls
                Process - The program clears the command prompt screen


Limitations
                - After a student is added or a student's scores were updated,
                the program needs to be reloaded in order for these changes to be seen.

*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define LSIZ 1280
#define RSIZ 100
#define TOTAL 4

// Declaration of necessary variables needed for the programs functionality

FILE *fptr = NULL;
FILE *fptw = NULL;
FILE *fptw2 = NULL;

char line[RSIZ][LSIZ];
int i = 0;
int tot = 0;
int ret;

char filename[] = "database.txt";
char altFilename[] = "database_alt.txt";

char userCommand[50];

struct studentInfo
{
    int studentID;
    char studentName[50];
    float mathScore;
    float englishScore;
    float scienceScore;
    float socialStudiesScore;
    float averageScore;
};

// "show-normal" command logic

void displayRecords()
{
    for(i = 0; i < tot; ++i)
    {
        // The code below will be run on lines where a student's ID is mentioned

        if((i % 6) == 0)
        {
            printf("\nStudent ID: %s\n", line[i]);
        }

        // The code below will be run on lines where a student's Name is mentioned

        else if((i % 6) == 1)
        {
            printf("Student Name: %s\n", line[i]);
        }

        // The code below will be run on lines where a student's Math Score is mentioned

        else if((i % 6) == 2)
        {
            printf("Math Score: %s\n", line[i]);
        }

        // The code below will be run on lines where a student's English Score is mentioned

        else if((i % 6) == 3)
        {
            printf("English Score: %s\n", line[i]);
        }

        // The code below will be run on lines where a student's Science Score is mentioned

        else if((i % 6) == 4)
        {
            printf("Science Score: %s\n", line[i]);
        }

        // The code below will be run on lines where a student's Social Studies Score is mentioned

        else if((i % 6) == 5)
        {
            printf("Social Studies Score: %s\n", line[i]);
        }

    }
}

// "find-name" command logic

void findStudentByName()
{
    int found = 0;
    char studentName[50];
    printf("Student Name: ");
    getchar();
    fgets(studentName, sizeof(studentName), stdin );
    studentName[strcspn(studentName, "\n")] = '\0';

    /* The for loop below is used by the program to find and print the information associated with
    a particular student name, if this student exists within the database. */

    for(i = 0; i < tot; ++i)
    {
        if(strcmp(studentName, line[i]) == 0)
        {
            printf("\nStudent ID: %s\n", line[i - 1]);
            printf("Student Name: %s\n", line[i]);
            printf("Math Score: %s\n", line[i + 1]);
            printf("English Score: %s\n", line[i + 2]);
            printf("Science Score: %s\n", line[i + 3]);
            printf("Social Studies Score: %s\n", line[i + 4]);
            found = 1;

            break;
        }
    }

    // Below code will run if the variable found has a value of 0, meaning that the student was not found within the database-text file.

    if(found == 0)
    {
        printf("Student Not Found\n");
    }
}

// "find-id" command logic

void findStudentById()
{
    int found = 0;
    int studentId;
    printf("Student ID: ");
    scanf("%d", &studentId);

    /* The for loop below is used by the program to find and print the information associated with
    a particular student ID, if this student ID exists within the database. */

    for(i = 0; i < tot; ++i)
    {
        if((atoi(line[i]) == studentId) && (i % 6) == 0)
        {
            printf("\nStudent ID: %s\n", line[i]);
            printf("Student Name: %s\n", line[i + 1]);
            printf("Math Score: %s\n", line[i + 2]);
            printf("English Score: %s\n", line[i + 3]);
            printf("Science Score: %s\n", line[i + 4]);
            printf("Social Studies Score: %s\n", line[i + 5]);
            found = 1;

            break;
        }
    }

    // Below code will run if the variable found has a value of 0, meaning that the student ID was not found within the database-text file.

    if(found == 0)
    {
        printf("Student Not Found\n");
    }
}

// "add" command logic

void addStudent()
{
    int found = 0;
    char studentName[50];
    printf("\nStudent Name: ");
    getchar();
    fgets(studentName, sizeof(studentName), stdin );
    studentName[strcspn(studentName, "\n")] = '\0';


    /* Code below will loop through loop through the lines of the file in search of a student which
    shares the same name as the one entered into the "add" command. If a student is found, the
    message "Student already in database" will be printed to the terminal */

    for(i = 0; i < tot; ++i)
    {
        if(strcmp(line[i], studentName) == 0)
        {
            found = 1;
            printf("Student already in database\n");

            break;
        }
    }

    /* If the student does not already exist within the databse, the user is the promoted by the following code to enter
    the student's Math, English, Science and Social Studies Score. This information is then stored within the struct "newStudent" before
    then being appended to the database file and printed to the terminal*/

    if(found == 0)
    {
        int idCount = 1;
        struct studentInfo newStudent;

        for(i = 0; i < tot; ++i)
        {
            if((i % 6) == 0)
            {
                idCount++;
            }
        }

        newStudent.studentID = idCount;
        strcpy(newStudent.studentName, studentName);


        printf("Student Math Score: ");
        scanf("%f", &newStudent.mathScore);

        printf("Student English Score: ");
        scanf("%f", &newStudent.englishScore);

        printf("Student Science Score: ");
        scanf("%f", &newStudent.scienceScore);

        printf("Student Social Studies Score: ");
        scanf("%f", &newStudent.socialStudiesScore);

        printf("\nNew Student ID: %d\n", newStudent.studentID);
        printf("New Student Name: %s\n", newStudent.studentName);
        printf("New Student Math Score: %.2f\n", newStudent.mathScore);
        printf("New Student English Score: %.2f\n", newStudent.englishScore);
        printf("New Student Science Score: %.2f\n", newStudent.scienceScore);
        printf("New Student Social Studies Score: %.2f\n", newStudent.socialStudiesScore);

        fprintf(fptw, "%d", newStudent.studentID);
        fprintf(fptw, "\n%s", newStudent.studentName);
        fprintf(fptw, "\n%.2f", newStudent.mathScore);
        fprintf(fptw, "\n%.2f", newStudent.englishScore);
        fprintf(fptw, "\n%.2f", newStudent.scienceScore);
        fprintf(fptw, "\n%.2f\b\n", newStudent.socialStudiesScore);

        printf("New Student added to database successfully (Reload to see changes)\n");
    }
}

// The below function is used by the "name-avg", "id-avg" and "show-avg" commands in order to properly store then calculate student's average score.

void calculateAverage(int i)
{
    struct studentInfo currentStudent;

    currentStudent.studentID = atoi(line[i]);
    strcpy(currentStudent.studentName, line[i + 1]);
    currentStudent.mathScore = atof(line[i + 2]);
    currentStudent.englishScore = atof(line[i + 3]);
    currentStudent.scienceScore = atof(line[i + 4]);
    currentStudent.socialStudiesScore = atof(line[i + 5]);
    currentStudent.averageScore = (currentStudent.mathScore + currentStudent.englishScore + currentStudent.scienceScore + currentStudent.socialStudiesScore) / TOTAL;

    printf("\nStudent ID: %d\n", currentStudent.studentID);
    printf("Student Name: %s\n", currentStudent.studentName);
    printf("Student Math Score: %.2f\n", currentStudent.mathScore);
    printf("Student English Score: %.2f\n", currentStudent.englishScore);
    printf("Student Science Score: %.2f\n", currentStudent.scienceScore);
    printf("Student Social Studies Score: %.2f\n", currentStudent.socialStudiesScore);
    printf("Average Score: %.2f\n", currentStudent.averageScore);
}

// "show-avg" command logic

/* This function has the task of displaying all student records with the average score of each student being included.
This is done by looping through each line of the file which contains a student's ID and the calling on the "calculateAverage()"
function and passing it the value of "i". At this point the "calculateAverage()" will print the lines which follow the one at position "i", which
contain the information of the student who posses the ID which the program has just iterated on*/

void calculateAverageScoreDisplay()
{
    for(i = 0; i < tot; i = i + 6)
    {
        calculateAverage(i);
    }
}

// "id-avg" command logic

/* The following function first prompts the user for the ID of the student who's average score is to be found.
It then looks through the database file for the ID which was enter and then passes the line number / the value of the "i" variable
to the "calculateAverage()" function, which then calculates and displays the Average Score of the student who has an ID which matches
the one entered by the user */

void calculateAverageScoreSingleID()
{
    printf("\nStudent ID: ");
    scanf("%s", userCommand);

    for(i = 0; i < tot; ++i)
    {
        if(strcmp(userCommand, line[i]) == 0)
        {
            calculateAverage(i);
            break;
        }

    }
}

/* The following function first prompts the user for the Name of the student who's average score is to be found.
It then looks through the database file for the Name which was enter and then passes the line number / the value of the "i" variable
to the "calculateAverage()" function, which then calculates and displays the Average Score of the student who's Name matches
the one entered by the user */

void calculateAverageScoreSingleName()
{
    printf("\nStudent Name: ");
    getchar();
    fgets(userCommand, sizeof(userCommand), stdin);
    userCommand[strcspn(userCommand, "\n")] = '\0';

    for(i = 0; i < tot; ++i)
    {
        if(strcmp(userCommand, line[i]) == 0)
        {
            calculateAverage(i - 1);
            break;
        }

    }
}

// "update-score" command logic

void updateScoreByID()
{
    struct studentInfo studentUpdate;
    float tempScore;
    int subjectChoice = 0;
    int dest = 0;
    int subjectDest = 0;

    int valid = 0;
    printf("\nStudent ID: ");
    scanf("%s", userCommand);

    /* Below code is responsible for checking whether a student with the ID entered by the user exists. If so, then
    prompts the user for the subject area who's score is to be changes, with 1 being Math, 2 being English, 3 being
    Science and 4 being Social Studies. The below code also makes use of the struct "studentUpdate", for storing the data
    of the student who's score is to be changed, prior to the change */

    for(i = 0; i < tot; ++i)
    {
        if(strcmp(line[i], userCommand) == 0)
        {
            studentUpdate.studentID = atoi(line[i]);
            strcpy(studentUpdate.studentName, line[i + 1]);
            studentUpdate.mathScore = atof(line[i + 2]);
            studentUpdate.englishScore = atof(line[i + 3]);
            studentUpdate.scienceScore = atof(line[i + 4]);
            studentUpdate.socialStudiesScore = atof(line[i + 5]);


            printf("\nStudent %s selected\n", studentUpdate.studentName);
            printf("Subject Score to be updated\n(1 - Math | 2 - English | 3 - Science | 4 - Social Studies): ");
            scanf("%d", &subjectChoice);

            dest = i;
        }
    }

    /* The below portion of code will be executed after the user has chosen the subject area who's score they would like to change.
    The program will first prompt the user for the new Score then it will store this in the struct updateStudent, replacing the previous score.
    The program will then output the new Score along with the previous Score of the subject Area for that particular student. */

    if(subjectChoice == 1)
    {
        printf("\nNew Math Score: ");
        scanf("%f", &tempScore);

        printf("\nPrevious Math Score: %.2f", studentUpdate.mathScore);
        studentUpdate.mathScore = tempScore;
        printf("\nNew Math Score: %.2f\n", studentUpdate.mathScore);

        valid = 1;
        subjectDest = dest + 2;
    }

    else if(subjectChoice == 2)
    {
        printf("\nNew English Score: ");
        scanf("%f", &tempScore);

        printf("\nPrevious English Score: %.2f", studentUpdate.englishScore);
        studentUpdate.englishScore = tempScore;
        printf("\nNew English Score: %.2f\n", studentUpdate.englishScore);

        valid = 1;
        subjectDest = dest + 3;
    }

    else if(subjectChoice == 3)
    {
        printf("\nNew Science Score: ");
        scanf("%f", &tempScore);

        printf("\nPrevious Science Score: %.2f", studentUpdate.scienceScore);
        studentUpdate.scienceScore = tempScore;
        printf("\nNew Math Score: %.2f\n", studentUpdate.scienceScore);

        valid = 1;
        subjectDest = dest + 4;
    }

    else if(subjectChoice == 4)
    {
        printf("\nNew Social Studies Score: ");
        scanf("%f", &tempScore);

        printf("\nPrevious Social Studies Score: %.2f", studentUpdate.socialStudiesScore);
        studentUpdate.socialStudiesScore = tempScore;
        printf("\nNew Social Studies Score: %.2f\n", studentUpdate.socialStudiesScore);

        valid = 1;
        subjectDest = dest + 5;
    }
    else if(subjectChoice == 0)
    {
        printf("\nInvalid Command\n");
    }

    /* The following code is responsible for copying the contents of the database file, along with the updated score, to the alternate database file.
    At which point the program will then delete the old database file and rename the "database_alt.txt" file to "database.txt" and then recreate the "database_alt" file*/

    if(valid == 1)
    {
        for(i = 0; i < tot; ++i)
        {
            if((i == subjectDest))
            {
                if(subjectChoice == 1)
                {
                    sprintf(userCommand, "%.2f", studentUpdate.mathScore);
                    fprintf(fptw2, "%s\n", userCommand);
                }

                else if(subjectChoice == 2)
                {
                    sprintf(userCommand, "%.2f", studentUpdate.englishScore);
                    fprintf(fptw2, "%s\n", userCommand);
                }

                else if(subjectChoice == 3)
                {
                    sprintf(userCommand, "%.2f", studentUpdate.scienceScore);
                    fprintf(fptw2, "%s\n", userCommand);
                }

                else if(subjectChoice == 4)
                {
                    sprintf(userCommand, "%.2f", studentUpdate.socialStudiesScore);
                    fprintf(fptw2, "%s\b\n", userCommand);
                }

            }

            else
            {
                fprintf(fptw2, "%s\n", line[i]);
            }
        }

        fclose(fptr);
        fclose(fptw);
        fclose(fptw2);

        /* The "ret" variable will be equal to 0 if both the remove operation and rename operation run, otherwise
        it will have a value other than 0, causing the else portion of the below IF-ELSE structure to run */

        ret = remove(filename) + rename(altFilename, filename);

        if(ret == 0)
        {
          printf("Operation Successful\n");
          printf("Restart program to see changes\n");
        }

        else
        {
          printf("Operation Error\n");
        }
    }
}

// "help" command logic

void help()
{
    printf("\n");
    printf("  *********************************************** Command List ************************************************\n");
    printf("  * help         - Show this help screen                                                                      *\n");
    printf("  * cls          - Clear terminal screen                                                                      *\n");
    printf("  * show-normal  - Show normal display screen                                                                 *\n");
    printf("  * show-avg     - Show display screen with average-score calculations                                        *\n");
    printf("  * find-name    - Find student by name in database                                                           *\n");
    printf("  * find-id      - Find student by their associated ID                                                        *\n");
    printf("  * add          - Add student to database                                                                    *\n");
    printf("  * id-avg       - Return average-score of a student with a particular ID                                     *\n");
    printf("  * name-avg     - Return average-score of a student with a particular name                                   *\n");
    printf("  * update-score - Allows for the updating of a student's score for a particular subject if their ID is known *\n");
    printf("  *************************************************************************************************************\n");
}

// Main Function

int main()
{

    /* Code portion below is used to open the necessary "database.txt" and "database_alt.txt" files.
    It is also responsible for creating an array called "line" and assigning each line of the file as one of its elements.
    This allows for each line of the file to be accessed in the same way an element within an array could be accessed */

    fptr = fopen("database.txt", "r");
    fptw = fopen("database.txt", "a");
    fptw2 = fopen("database_alt.txt", "w");

    while(fgets(line[i], LSIZ, fptr))
	{
        line[i][strlen(line[i]) - 1] = '\0';
        i++;
    }

    tot = i;

    // Below call of help() function is used to print the program help menu on program startup.

    help();

    // Main Loop of Program

    while(1)
    {
        printf("\nhelp> ");
        scanf("%s", userCommand);

        // Code below will run if the "exit" keyword is passed to the program

        if(strcmp(userCommand, "exit") == 0)
        {
            break;
        }

        // Code below will run if the "show-normal" keyword is passed to the program

        else if(strcmp(userCommand, "show-normal") == 0)
        {
            system("cls");
            displayRecords();
        }

        // Code below will run if the "show-avg" keyword is passed to the program

        else if(strcmp(userCommand, "show-avg") == 0)
        {
            system("cls");
            calculateAverageScoreDisplay();
        }

        // Code below will run if the "find-name" keyword is passed to the program

        else if(strcmp(userCommand, "find-name") == 0)
        {
            system("cls");
            findStudentByName();
        }

        // Code below will run if the "find-id" keyword is passed to the program

        else if(strcmp(userCommand, "find-id") == 0)
        {
            system("cls");
            findStudentById();
        }

        // Code below will run if the "add" keyword is passed to the program

        else if(strcmp(userCommand, "add") == 0)
        {
            system("cls");
            addStudent();
        }

        // Code below will run if the "id-avg" keyword is passed to the program

        else if(strcmp(userCommand, "id-avg") == 0)
        {
            system("cls");
            calculateAverageScoreSingleID();
        }

        // Code below will run if the "name-avg" keyword is passed to the program

        else if(strcmp(userCommand, "name-avg") == 0)
        {
            system("cls");
            calculateAverageScoreSingleName();
        }

        // Code below will run if the "update-score" keyword is passed to the program

        else if(strcmp(userCommand, "update-score") == 0)
        {
            system("cls");
            updateScoreByID();
        }

        // Code below will run if the "cls" keyword is passed to the program

        else if(strcmp(userCommand, "cls") == 0)
        {
            system("cls");
        }

        // Code below will run if the "help" keyword is passed to the program

        else if(strcmp(userCommand, "help") == 0)
        {
            help();
        }

        // Code below will run if an invalid command is passed to the program

        else
        {
            printf("\nInvalid Command\n");
        }
    }

    printf("\n");
    fclose(fptr);
    fclose(fptw);
    fclose(fptw2);

    return 0;
}
